### ISSUE TITLE
LoaderLock问题

### ISSUE THREAD

**Issue by oksbsb** [anhkgg/SuperDllHijack#1]
根据 https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-best-practices

You should never perform the following tasks from within DllMain:

    Call LoadLibrary or LoadLibraryEx (either directly or indirectly). This can cause a deadlock or a crash.

在DllMain里面调用LoadLibrary 会死锁，测试过这种情况么

**Comment by anhkgg** [comment]
是的，但目前使用是没有遇到问题的

**Comment by anhkgg** [comment]
另外也有解决方法的，自行load模块

**Comment by yves-yl** [comment]
vs2019 下测试得到:
win10 x86运行良好.
win10 x64 无法使用 PEB_LDR_DATA* NtGetPebLdr(void* peb). \
PEB_LDR_DATA* ldr = NtGetPebLdr(peb); ldr 为 NULL
win10 x64 无法根据dll.def到处文件.需要加"__declspec(dllexport)"进行导出
