### ISSUE TITLE
win10 vs2019 x64 需要修改代码后才能使用

### ISSUE THREAD

**Issue by yves-yl** [anhkgg/SuperDllHijack#2]
vs2019 下测试得到:
win10 x86运行良好.

win10 x64 无法使用 void* NtCurrentPeb(). 
需要将 return (void*)__readgsqword(0x30)
改成  return (void*)__readgsqword(0x60)
win10 x64 无法根据dll.def导出文件.需要加"__declspec(dllexport)"进行导出

**Comment by kiwings** [comment]
> vs2019 下测试得到:
> win10 x86运行良好.
> 
> win10 x64 无法使用 void* NtCurrentPeb().
> 需要将 return (void*)__readgsqword(0x30)
> 改成 return (void*)__readgsqword(0x60)
> win10 x64 无法根据dll.def导出文件.需要加"__declspec(dllexport)"进行导出

感谢鸭，但是我测试发现
返回值为0x30时，win10 x64下使用x86编译的程序第一次运行会崩溃，但是之后运行均正常，但是使用x64编译的程序则在调用原始dll的导出函数时就崩溃。
修改返回值为0x60，win10 x64下使用x86编译的程序第一次运行会崩溃，但是之后运行均正常，但是使用x64编译的程序则在程序结束后崩溃。

**Comment by 6769** [comment]
win7 x64 x86,  proved ^_^

What I do : 
- modify export function to automatically add dll export IAT
```cpp
#define EXPORT __declspec(dllexport)
extern "C" {
	EXPORT
	int TestExport(int a, int b)
	{
		return a + b;
	}
}
```
- replace `return (void*)__readgsqword(0x30)` to  `return (void*)__readgsqword(0x60)`
